security:

    password_hashers:
        App\Entity\Member:
            algorithm: auto

    providers:
        member_provider:
            entity:
                class: App\Entity\Member
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: member_provider
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator

    access_control:
        - { path: ^/api, roles: ROLE_USER }
